INSERT INTO NACIONALIDAD (ID_NACIONALIDAD, NACIONALIDAD, PAIS) VALUES (1, 'Argentina', 'Argentina');

INSERT INTO AUTOR (ID_AUTOR, NOMBRE, APELLIDO, FECHA_NACIMIENTO, ID_NACIONALIDAD) VALUES (1, 'Pablo', 'Cohelo', '2018-12-22', 1 );

INSERT INTO PUBLICACION (ID_PUBLICACION, FECHA_PUBLICACION, TITULO, ID_AUTOR) VALUES (1, '2018-12-13', 'Primera publicacion', 1 );
			